import { Geist, Geist_Mono, Audiowide, Stalinist_One } from "next/font/google";

import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});
const audiowide = Audiowide({
    variable: "--font-audiowide",
    subsets: ["latin"],
    weight: "400",
});
const stalinistone = Stalinist_One({
    variable: "--font-stalinistone",
    weight: "400",
    subsets: ["latin"],
});

export const metadata = {
    title: "Generate Password",
    description: "Generated By NotAboutJerry",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${audiowide.variable} ${stalinistone.variable} `}
            >
                {children}
            </body>
        </html>
    );
}
